name: Retag DockerHub image to Tencent TCR

on:
  workflow_dispatch:

jobs:
  retag:
    runs-on: ubuntu-latest
    steps:
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login Tencent TCR
        uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TCR_USERNAME }}
          password: ${{ secrets.TCR_PASSWORD }}

      - name: Pull from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mental-health:latest

      - name: Tag for TCR
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mental-health:latest \
            ccr.ccs.tencentyun.com/mental/mental-health:latest

      - name: Push to TCR
        run: |
          docker push ccr.ccs.tencentyun.com/mental/mental-health:latest
